#!/usr/bin/env python3
"""Generate data/arm-midr.toml from util-linux's sys-utils/lscpu-arm.c.

    curl -sSfL https://raw.githubusercontent.com/util-linux/util-linux/53cd4fb62b027bc25437c06a1e3a002574c00972/sys-utils/lscpu-arm.c -o /tmp/lscpu-arm.c
    scripts/gen-arm-midr.py /tmp/lscpu-arm.c > data/arm-midr.toml

lscpu-arm.c is GPL-2.0-or-later, compatible with this project's GPL-3.0-or-later. When updating,
change the pinned commit in COMMIT and in the command above.
"""
import re
import sys

COMMIT = "53cd4fb62b027bc25437c06a1e3a002574c00972"

# Apple's hypervisor reports part 0x000 for every Linux guest on Apple Silicon. lscpu-arm.c maps
# 0x61/0x000 to "Swift" (a 32-bit core from 2012), which would mislabel every such VM, so it is
# left out: an unknown name is hidden, a wrong one would be printed.
OMIT = {(0x61, 0x000)}


def main(path):
    source = open(path, encoding="utf-8").read()
    copyright_lines = re.findall(r"^\s*\*\s*(Copyright .*)$", source, re.M)

    parts = {}
    for array, body in re.findall(r"static const struct id_part (\w+)\[\] = \{(.*?)\n\};", source, re.S):
        parts[array] = [
            (int(pid, 16), name)
            for pid, name in re.findall(r"\{\s*(0x[0-9a-fA-F]+)\s*,\s*\"([^\"]+)\"\s*\}", body)
        ]

    table = re.search(r"static const struct hw_impl hw_implementer\[\] = \{(.*?)\n\};", source, re.S).group(1)
    implementers = [
        (int(iid, 16), array, name)
        for iid, array, name in re.findall(r"\{\s*(0x[0-9a-fA-F]+)\s*,\s*(\w+)\s*,\s*\"([^\"]+)\"", table)
    ]

    out = [
        "# ARM CPU implementer and part names, keyed by MIDR fields.",
        "#",
        "# GENERATED by scripts/gen-arm-midr.py from util-linux sys-utils/lscpu-arm.c; regenerate",
        "# rather than editing by hand. That file is GPL-2.0-or-later:",
    ]
    out += [f"#   {line}" for line in copyright_lines]
    out += [
        "#",
        "# Deliberately omitted: implementer 0x61 part 0x000 (see the generator for why).",
        "",
        f'ref = "https://github.com/util-linux/util-linux/blob/{COMMIT}/sys-utils/lscpu-arm.c"',
        'stamp = "arm-midr@2026-09"',
        "",
    ]
    for iid, _, name in implementers:
        out += ["[[implementer]]", f"id = 0x{iid:02x}", f'name = "{name}"', ""]
    for iid, array, _ in implementers:
        for pid, name in parts.get(array, []):
            if (iid, pid) in OMIT:
                continue
            out += ["[[part]]", f"implementer = 0x{iid:02x}", f"id = 0x{pid:03x}", f'name = "{name}"', ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
